### ISSUE TITLE
Steps not counted

### ISSUE THREAD

**Issue by Baddeb** [mikeygray/noxie-clock#21]
I love this clock face, but it doesn't count steps. It is permanently showing '0 k'.  My app shows the steps, but I want to see them on my fitbit screen.

**Comment by mikeygray** [comment]
@Baddeb Thanks very much for letting me know. I've checked and this doesn't seem to happen on my test devices. Sounds to me like a permissions issue. Can you (using your phone) remove the watchface from your Fitbit, and then re-install it? When you re-install it should ask for a bunch of permissions to be granted, and one of them allows reading your steps.

You could also try this https://help.fitbit.com/articles/en_US/Help_article/2311.htm where it says:

> Many clock faces also require access to certain stats or other information. Note that turning off any of these permissions might cause the clock face to stop functioning. To adjust what a clock face has access to, tap the installed clock face > See all details > Permissions.

**Comment by Baddeb** [comment]
Hi Mikey, thanks for your reply. I did click on all permissions... I have noticed during the day that the '0 k' changed to '1k'... I would prefer all steps being counted, eg: 5,678...(rather than just showing '5k').Anyway, I'm really loving Noxie!Deb. On 6 May 2021 20:03, Mikey Gray ***@***.***> wrote:
@Baddeb Thanks very much for letting me know. I've checked and this doesn't seem to happen on my test devices. Sounds to me like a permissions issue. Can you (using your phone) remove the watchface from your Fitbit, and then re-install it? When you re-install it should ask for a bunch of permissions to be granted, and one of them allows reading your steps.
You could also try this https://help.fitbit.com/articles/en_US/Help_article/2311.htm where it says:

Many clock faces also require access to certain stats or other information. Note that turning off any of these permissions might cause the clock face to stop functioning. To adjust what a clock face has access to, tap the installed clock face > See all details > Permissions.

**Comment by mikeygray** [comment]
Should have closed this a while ago!
